function Static1 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  STATIC1 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  STATIC1 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  Static1 = importfile("/Users/rjhorn/Documents/DocumentsCopiedFromiCloud/GitHub/Research Techniques/Motion/Static0001.tsv", [12, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Feb-2020 16:33:01

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [12, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 115);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["ChestX", "ChestY", "ChestZ", "ASISLX", "ASISLY", "ASISLZ", "ASISRX", "ASISRY", "ASISRZ", "SacralX", "SacralY", "SacralZ", "supLatThighLX", "supLatThighLY", "supLatThighLZ", "supMedThighLX", "supMedThighLY", "supMedThighLZ", "infLatThighLX", "infLatThighLY", "infLatThighLZ", "infMedThighLX", "infMedThighLY", "infMedThighLZ", "supLatThighRX", "supLatThighRY", "supLatThighRZ", "supMedRightRX", "supMedRightRY", "supMedRightRZ", "infLatThighRX", "infLatThighRY", "infLatThighRZ", "inMedThighRX", "inMedThighRY", "inMedThighRZ", "latKneeLX", "latKneeLY", "latKneeLZ", "medKneeLX", "medKneeLY", "medKneeLZ", "latKneeRX", "latKneeRY", "latKneeRZ", "medKneeRX", "medKneeRY", "medKneeRZ", "supAntShankLX", "supAntShankLY", "supAntShankLZ", "supPostShankLX", "supPostShankLY", "supPostShankLZ", "infAntShankLX", "infAntShankLY", "infAntShankLZ", "infPostShankLX", "infPostShankLY", "infPostShankLZ", "supAntShankRX", "supAntShankRY", "supAntShankRZ", "supPostShankRX", "supPostShankRY", "supPostShankRZ", "infAntShankRX", "infAntShankRY", "infAntShankRZ", "infPostShankRX", "infPostShankRY", "infPostShankRZ", "heelLeftX", "heelLeftY", "heelLeftZ", "heelRightX", "heelRightY", "heelRightZ", "toeLeftX", "toeLeftY", "toeLeftZ", "toeRightX", "toeRightY", "toeRightZ", "latAnkleLX", "latAnkleLY", "latAnkleLZ", "medAnkleLX", "medAnkleLY", "medAnkleLZ", "latAnkleRX", "latAnkleRY", "latAnkleRZ", "medAnkleRX", "medAnkleRY", "medAnkleRZ", "lateralFootLX", "lateralFootLY", "lateralFootLZ", "proximalFootLX", "proximalFootLY", "proximalFootLZ", "distalFootLX", "distalFootLY", "distalFootLZ", "lateralFootRX", "lateralFootRY", "lateralFootRZ", "proximalFootRX", "proximalFootRY", "proximalFootRZ", "distalFootRX", "distalFootRY", "distalFootRZ", "VarName115"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];
opts = setvaropts(opts, 115, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 115, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Static1 = readtable(filename, opts);

end