function running0002S1 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  RUNNING0002S1 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  RUNNING0002S1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  running0002S1 = importfile("/Users/rjhorn/Documents/DocumentsCopiedFromiCloud/GitHub/Research Techniques/EMG/running0002_S1.tsv", [12, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 10-Feb-2020 21:48:03

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [12, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 25);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["ASISLX", "ASISLY", "ASISLZ", "ASISRX", "ASISRY", "ASISRZ", "medialKneeX", "medialKneeY", "medialKneeZ", "lateralKneeX", "lateralKneeY", "lateralKneeZ", "medialMalleolusX", "medialMalleolusY", "medialMalleolusZ", "lateralMalleolusX", "lateralMalleolusY", "lateralMalleolusZ", "toeX", "toeY", "toeZ", "sacralX", "sacralY", "sacralZ", "VarName25"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];
opts = setvaropts(opts, 25, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 25, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
running0002S1 = readtable(filename, opts);

end